[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_forge"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@arbitrum/=node_modules/@arbitrum/",
    "@chainlink/=node_modules/@chainlink/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    "@offchainlabs/=node_modules/@offchainlabs/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@scroll-tech/=node_modules/@scroll-tech/",
    "@zksync/=node_modules/@zksync/",
    "forge-std/=lib/forge-std/src/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
    "solady/=node_modules/solady/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
